apiVersion: v1
kind: ConfigMap
metadata:
  name: snowflake-config
  namespace: demo-namespace
data:
  account: jd98257.canada-central.azure
  user: prashant887
  #password: prashantL@887
  warehouse: COMPUTE_WH
  database: DEMO_DB
  schema: PUBLIC
  role: ACCOUNTADMIN

---
apiVersion: v1
kind: Secret
metadata:
  name: snowflake-secret
  namespace: demo-namespace
type: Opaque
data:
  password: cHJhc2hhbnRMQDg4Nwo=

