apiVersion: v1
kind: Service
metadata:
  name: snowflake-web-app-service
  namespace: demo-namespace
spec:
  selector:
    app: snowflake-web-app
  ports:
    - port: 8085
      protocol: TCP
      targetPort: 9090
      #nodePort: 31525
      name: http
  type: ClusterIP
        #NodePort
        #LoadBalancer
  #externalIPs:
  #- 192.168.0.10

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snowflake-web-app
  namespace: demo-namespace
spec:
  selector:
    matchLabels:
      app: snowflake-web-app
  replicas: 1
  template:
    metadata:
      labels:
        app: snowflake-web-app
    spec:
      #volumes:
      #  - name: log-path
          #hostPath:
          #  path: /Users/pl465j/Documents/KubeFlaskApp/log
       #   persistentVolumeClaim:
       #     claimName: task-pv-claim
      containers:
      - name: snowflake-web-app
        image: snowflake_web_app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9090
        env:
        - name: ENV
          value: Testing
        - name: USER
          valueFrom:
            configMapKeyRef:
              name: snowflake-config
              key: user
        - name: PASSWD
          valueFrom:
            secretKeyRef:
              name: snowflake-secret
              key: password
        - name: ACC
          valueFrom:
            configMapKeyRef:
              name: snowflake-config
              key: account
        - name: WH
          valueFrom:
            configMapKeyRef:
              name: snowflake-config
              key: warehouse
        - name: DB
          valueFrom:
            configMapKeyRef:
              name: snowflake-config
              key: database
        - name: SCHEMA
          valueFrom:
            configMapKeyRef:
              name: snowflake-config
              key: schema
        - name: ROLE
          valueFrom:
            configMapKeyRef:
              name: snowflake-config
              key: role
         #volumeMounts:
         # - name: log-path
          #  mountPath: /log/

