---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sf-app-ingress
  namespace: demo-namespace
spec:
  rules:
  - host: kubernetes.docker.internal
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: snowflake-web-app-service
            port:
              number: 80
